# Mod
version = 26.3.0.0
mod_id = replikaentropie
mod_name = Replika Entropie
group = net.blay09.mods
description=Research tech, unlock gadgets, and fabricate the sun - in traditional Blockheads flavor.
homepage=https://mods.twelveiterations.com/minecraft/replika-entropie
sources=https://github.com/TwelveIterations/ReplikaEntropie/issues
issues=https://github.com/TwelveIterations/ReplikaEntropie/issues
discord=https://discord.gg/VAfZ2Nau6j
license=All Rights Reserved
mod_author = BlayTheNinth
credits = BlayTheNinth

# Publishing
curseforge_project_id = 1350519
curseforge_environments = Client,Server
modrinth_project_id = PGaw4JMK
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Build
java_version = 25
include_fabric=true
include_neoforge=false
include_forge=false

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
